#!/bin/sh

ProgName='fhirbase'
  
sub_help(){
    echo "Usage: $ProgName <subcommand> [options]\n"
    echo "Subcommands:"
    echo "    bar   Do bar"
    echo "    baz   Run baz"
    echo ""
    echo "For help with each subcommand run:"
    echo "$ProgName <subcommand> -h|--help"
    echo ""
}
  
  
subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        executor="./${subcommand}/run"
        if [ -f ${executor} ]; then
            $executor $@
        else
          echo "Error: '$subcommand' is not a known subcommand." >&2
          echo "       Run '$ProgName --help' for a list of known subcommands." >&2
          exit 1
        fi
        ;;
esac