#!/usr/bin/env python3
import argparse
import os

from loader import iter_lines_from_external, iter_lines_from_files
from importer import import_lines


parser = argparse.ArgumentParser(description='Load data into fhirbase')
parser.add_argument('-d', '--dbname', required=True,
                    help='destination DB')
parser.add_argument('--fhir-version', metavar='version',
                    dest='fhir_version', default='3.3.0',
                    help='version of FHIR')

group = parser.add_mutually_exclusive_group(required=True)
group.add_argument(
    'files', metavar='file', nargs='*', default=[],
    help='load files in .json or .ndjson format (can be in archive)')
group.add_argument(
    '-b', '--bulk', metavar='url',
    dest='bulk', action='store',
    help='load files from external bulk API')
group.add_argument(
    '-s', '--synthea', metavar='directory',
    dest='synthea', action='store',
    help='load files from synthea output directory')
group.add_argument(
    '-e', '--external',
    metavar='url',
    dest='external', action='store',
    help='load files from external URL '
         '(in .json or .ndjson format, also can be in archive)')


if __name__ == '__main__':
    if not os.path.isfile('aidboxconv.jar'):
        raise RuntimeError('You don\'t have `aidboxconv.jar` installed')

    # TODO: install requirements: requests
    # TODO: install aidboxconv

    args = parser.parse_args()

    if args.files:
        import_lines(
            args.dbname, args.fhir_version, iter_lines_from_files(args.files))

    if args.bulk:
        pass

    if args.external:
        import_lines(
            args.dbname, args.fhir_version, iter_lines_from_external(args.external))

    if args.synthea:
        pass
